services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.example
    networks:
      - summarizer
    volumes:
      - db-data:/var/lib/postgresql/data

  backend-prod:
    restart: always
    build:
      context: ./backend
      dockerfile: prod.Dockerfile

    env_file:
      - .env.example
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - summarizer

  frontend-prod:
    container_name: angular
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    ports:
      - 4000:4000
    networks:
      - summarizer
    depends_on:
      - server

networks:
  summarizer:
    driver: bridge

volumes:
  db-data:
