services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.example
    networks:
      - summarizer
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "15432:80"
    env_file:
      - .env.example
    networks:
      - summarizer
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    # environment:
    #  ENV_VARIABLE: ${ENV_VARIABLE}
    #  NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - .env.example
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - db
    ports:
      - 3000:3000
    networks:
      - summarizer

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 4200:4200
    networks:
      - summarizer

networks:
  summarizer:
    driver: bridge

volumes:
  pgadmin-data:
  db-data:
